### ISSUE TITLE
Installation fails with inability to connect to mysql even with .env filled.

### ISSUE THREAD

**Issue by weisisheng** [wzulfikar/docker-sendportal#1]
Getting asked questions at the end of the installation and I input the same variables as in the .env which then fails.

Also new to laravel and wondering if the blank pusher fields need to be filled out. there were no instructions with regards to this. I.e. PUSHER_APP_ID=, PUSHER_APP_KEY=, PUSHER_APP_SECRET=

Thanks in advance for any tips or tricks.

**Comment by weisisheng** [comment]
I am moving to another framework

**Comment by stewartmckee** [comment]
In case anyone else hits this, you can make sure all your docker containers are in the same network eg

```
docker network create sendportal_network
docker run --name sendportal --network sendportal_network ...etc
```
